services:
  
  model:
    build: ./model
    image: pathinker/finalytics:model-1.0
    env_file:
      - ../rag/.env
    ports:
      - "8000:8000"
    networks:
      - backend
    volumes:
      - ../rag:/app/rag:cached
    #deploy:
    #  resources:
    #    reservations:
    #      devices:
    #        - driver: nvidia
    #          count: all
    #         capabilities: [gpu]
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://model:8000/health || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 5
      start_period: 120s

  controller: 
    build: ./controller
    image: pathinker/finalytics:controler-1.0
    env_file:
      - ../services/.env
    ports:
      - "8100:8100"
    networks:
      - backend
    depends_on:
      - model
    volumes:
      - ../services:/app/services:cached
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://controller:8100/health || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 5
      start_period: 120s

  view:
    build: ./view
    command: tail -f /dev/null
    image: pathinker/finalytics:view-1.0
    stdin_open: true # -i
    tty: true        # -t
    ports:
      - "8500:8500"
    networks:
      - backend
    depends_on:
      - controller
    volumes:
      - ../:/app:cached  

networks:
  backend:
    driver: bridge